### ISSUE TITLE
Unable to enable any cheat while the old version works fine

### ISSUE THREAD

**Issue by zwk2160** [K3nny567/Cheat-Menu-Framework#1]
check your work carefully, I could activate anything from your GitHub release but everything work fine with your file in f95zone, lona version 8.8.3.3 clean installation

**Comment by K3nny567** [comment]
Minimum game version is 8.8.7.0 for the github releases. The current release here now also requires UMM (as of v1.0rc1)

Once v1.0 is done the release that is currently on F95 will be updated to the same release as here at that time.

MCM will remain as a secondary branch here though for older game versions.
