### ISSUE TITLE
"mod.json cannot find accesses to the Module folder, which prevents mods from being opened."

### ISSUE THREAD

**Issue by 96flo** [K3nny567/Cheat-Menu-Framework#11]
"If you don't mind, could you explain more specifically where to place the Modules folder, because when they are inside the CheatModFramework folder, they don't work, neither the menu nor the modules.

**Comment by 96flo** [comment]
I'm dump, nvm

**Comment by K3nny567** [comment]
You're not the first to install the mod incorrectly, nor will you be the last.

Glad you figured it out though.
