### ISSUE TITLE
Cant open Cheat Menu

### ISSUE THREAD

**Issue by NixonGreat** [K3nny567/Cheat-Menu-Framework#18]
every function is fine,except for F9
I can hear the sound of opening cheat menu,but nothing happens

**Comment by K3nny567** [comment]
I'm gonna need more details than that.

Mod version
Game version
Screenshots of the mod folder contents
Steps taken to install the mod.

If using the latest version of the mod, the menu hotkey has been changed to the Back Quote key [ &#96; &#126; ] as part of the move away from Cheat Menu being a debug menu.

Make sure all updates of the mod are a clean install as there have been some file renaming in a couple of updates.

**Comment by K3nny567** [comment]
Try the latest commit.

[See this post on F95 for details on how to change the new hotkey via GameCheats.ini](https://f95zone.to/posts/14094299/)

**Comment by NixonGreat** [comment]
Many Thanks

________________________________
发件人: Kenny ***@***.***>
发送时间: 2024年6月25日 14:41
收件人: K3nny567/Cheat-Menu-Framework ***@***.***>
抄送: NixonGreat ***@***.***>; Author ***@***.***>
主题: Re: [K3nny567/Cheat-Menu-Framework] Cant open Cheat Menu (Issue #18)


Try the latest commit.

See this post on F95 for details on how to change the new hotkey via GameCheats.ini<https://f95zone.to/posts/14094299/>

―
