### ISSUE TITLE
AIO file is missing a few text files

### ISSUE THREAD

**Issue by Blitzerfnv** [K3nny567/Cheat-Menu-Framework#2]
I downloaded the AIO file, and the Ultra Mod Manager, and these three errors come up. Fresh install. 
![image](https://github.com/K3nny567/Cheat-Menu-Framework/assets/39604146/602fb7bc-8c0d-476b-a073-3985fc7aa158)
![image](https://github.com/K3nny567/Cheat-Menu-Framework/assets/39604146/78e3a64b-91fa-458e-bef6-3ed2303021fb)
![image](https://github.com/K3nny567/Cheat-Menu-Framework/assets/39604146/cc72490a-6f2d-440d-bc7b-dbda9704e587)
Not sure why is is happening.

**Comment by K3nny567** [comment]
Oops... I messed up the filter when they got split.
For now grab the following CheatModules and get the text files that way:

- Race Changer
- Morality Editor
- Summons Menu

After I get the filter corrected I'll re-attached the fixed AIO to the current release.

**Comment by K3nny567** [comment]
The issue has been fixed and the corrected AIO file has been attached to the release.
