### ISSUE TITLE
[Error-0930] Duplicate status, change race and change hair color

### ISSUE THREAD

**Issue by SadoYasashii** [K3nny567/Cheat-Menu-Framework#20]
Hi. On the version of the game 0.9.3.0 found 3 errors. I attach their logs.

On the status Vertigo, when selecting work both or separately, but it is worth to lower any stack indicator to 0-1 immediately error.

When changing hair, if you lower show to 0-1 immediately error, the color above changes.

At any choice to change race, immediately an error, no matter what race.

[error_log20241013_1005_39_Stats.txt](https://github.com/user-attachments/files/17354750/error_log20241013_1005_39_Stats.txt)
[error_log20241013_1007_44_Set Hair Color.txt](https://github.com/user-attachments/files/17354751/error_log20241013_1007_44_Set.Hair.Color.txt)
[error_log20241013_1010_06_Change Race.txt](https://github.com/user-attachments/files/17354752/error_log20241013_1010_06_Change.Race.txt)

**Comment by SadoYasashii** [comment]
It was not possible to cause the hair color change problem again, it appeared when the vertigo status was standing... he probably just caught one problem.

![Stats](https://github.com/user-attachments/assets/02d49cb0-adf6-4e45-bd7b-0f9272bf91ba)
![Change Race](https://github.com/user-attachments/assets/97b088d9-8230-4686-aab7-3aa8dd25be76)

**Comment by SadoYasashii** [comment]
Another problem. If any status is reduced to 0-1, it will immediately generate an error as with a duplicate status. It is necessary to check the script for compliance with the condition, probably there are changes.

![изображение](https://github.com/user-attachments/assets/ecdaa70a-beef-43c0-a21c-f1f0ba668d6b)

**Comment by K3nny567** [comment]
The 2 vertigo states are correct, there is 1 for non-deepone and 1 for deepone.
So that is not actually a duplicate.

The second Vertigo should be the DeepOne version of the status.

There is nothing wrong with the hair color editor, that log is for the stats editor (which has been fixed)
