### ISSUE TITLE
The cheats mod fails to load

### ISSUE THREAD

**Issue by AbhishekSawant394** [K3nny567/Cheat-Menu-Framework#6]
![Screenshot 2024-03-11 000644](https://github.com/K3nny567/Cheat-Menu-Framework/assets/140789087/6855cbdb-bdf4-4d43-bdb5-73d33bfeb9be)

**Comment by K3nny567** [comment]
That's an issue with UltraModManager.

[v1.0rc3](../releases/tag/v1.0rc3) of Cheat Menu Framework makes use of the dependency system introduced by UMM, but that system is bugged in the current version of UMM (1.2.0).

Here is the fix for [UMM (1.2.1)](../files/14495008/UltraModManager-1.2.1.zip)
